import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* 
  The root layout is the outermost wrapper for all pages of the app.
  It is responsible for rendering the navbar and the main content of the current page. 
*/
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen overflow-hidden">
          <nav className="fixed w-full h-16 z-30 px-4  bg-[#053C36] ">
            <Navbar />
          </nav>
          <div className="flex flex-1 flex-col pt-16">
            <main className="flex-1 overflow-y-auto border-l bg-[#f4f7f7]">
              {children}
            </main>
            <Toaster />
          </div>
        </div>
      </body>
    </html>
  );
}
